export const view = {
  SET_LOADING_STATUS: 'SET_LOADING_STATUS',
  SET_TOAST_MESSAGE: 'SET_TOAST_MESSAGE',
};

export const weather = {
  FETCH_WEATHER_DATA_SUCCESS: 'FETCH_WEATHER_DATA_SUCCESS',
  FETCH_WEATHER_DATA_FAILURE: 'FETCH_WEATHER_DATA_FAILURE',
};
